name: Autograding
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    # add id to action so outputs can be used
    - uses: education/autograding@v1
      id: autograder
      continue-on-error: true

    # make dir for badges
    - name: badges branch and make dir
      run: |
        git checkout --orphan badges
        git rm -rf .
        mkdir -p .github/badges

    # make points badge
    - name: points badge
      uses: emibcn/badge-action@v1
      with:
        LABEL: 'Points'
        STATUS: ${{ steps.autograder.outputs.points }}
        LABEL-COLOR: 2f496e
        COLOR: 2988bc
        SCALE: 2
        STYLE: flat
        path: '.github/badges/points.svg'

    - name: Upload badge as artifact
      uses: actions/upload-artifact@v2
      with:
        name: badge
        path: '.github/badges/points.svg'
        if-no-files-found: error
        retention-days: 1

    # commit and push badge if score has changed
    - name: Commit badge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add '.github/badges/points.svg'
        git commit -m "Add/Update badge"
      continue-on-error: true
    - name: Push badge commit
      uses: ad-m/github-push-action@master
      if: success()
      with:
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: badges

    # fail job if autograder returns failed
    # outcome can be 'success', 'failure', 'cancelled', or 'skipped'
    # trigger fail either on !success or on failure depending on preference
    - name: check autograder pass fail
      if: ${{ steps.autograder.outcome != 'success' }}
      # if: ${{ steps.autograder.outcome == 'failure' }}
      # if: ${{ failure }}
      run: exit 1