name: GitHub Classroom Workflow

on:
  create:
    branches:
    - '*'
    - '!badges'
  push:
    branches:
    - '*'
    - '!badges'

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: DCI-EdTech/autograding-action@main